version: "3"

services:
  app:
    build:
      context: client
    image: nickthesick/course-selector_app
    depends_on:
      - couchdb
    restart: always
    container_name: course-selector
    networks:
      - course
    environment:
      DB_URL: 'course:password@couchdb'
    ports: 
      - 3000:3000
  couchdb:
    image: couchdb:2.3
    restart: always
    container_name: couchdb
    networks:
      - course
    volumes:
      - couchdb:/opt/couchdb/data
    environment:
      COUCHDB_USER: 'course'
      COUCHDB_PASSWORD: 'password'
  server:
    build:
      context: server
    image: nickthesick/course-selector_server
    depends_on: 
      - couchdb
    restart: always
    container_name: course-selector-server
    networks: 
      - course
    environment: 
      DB_URL: 'course:password@couchdb'
  tasker:
    image: strm/tasker
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock
    environment:
      configuration: |
        logging:
          level:
              ROOT: WARN
              org.springframework.web: WARN
              sh.strm: DEBUG
        schedule:
          - every: hour
            task: scrape-courses
        tasks:
          docker:
            - name: scrape-courses
              image: pstauffer/curl:latest
              network: client_course # docker-compose prepends with client_ needed to be able to connect to the same network
              script:
                - curl course-selector-server:9000/courses/ # This can be used to send notifications to an express server that will actually scrape or not
volumes: 
  couchdb:
networks: 
  course:
